version: '3.7'

services:
  nextjs:
    container_name: nextjs-production
    build: .
    environment:
      NODE_ENV: production
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-production
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
